/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-10-23 09:46:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reserveList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>예매확인/취소</title>\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.3.1.js\"\r\n");
      out.write("  integrity=\"sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=\"\r\n");
      out.write("  crossorigin=\"anonymous\">\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("    /* 전체 사이즈 조정 */\r\n");
      out.write("    \r\n");
      out.write("    ul, li, a{list-style: none; margin: 0px; padding: 0px; text-decoration: none; color: black;}\r\n");
      out.write("    \r\n");
      out.write("    div{box-sizing: border-box;}\r\n");
      out.write("    #wrapper{overflow: hidden;min-width: 990px;min-height: 100%; border: 1px solid black;}\r\n");
      out.write("    #header{height: 193px; border: 1px solid black;}\r\n");
      out.write("    #container{height: 100%; border: 1px solid black; background: #f4f4f4;}\r\n");
      out.write("    #footer{height: 153px; border: 1px solid black;}\r\n");
      out.write("    \r\n");
      out.write("    /* 990px 고정 사이즈 */\r\n");
      out.write("    #h_inner{width: 990px; height: 100%; margin: 0px auto;}\r\n");
      out.write("    #c_inner{width: 990px; height: 1300px; margin: 0px auto; padding: 70px 0 250px 0px;}\r\n");
      out.write("    #f_inner{width: 990px; margin: 0px auto;}\r\n");
      out.write("\r\n");
      out.write("    /* top 버튼 */\r\n");
      out.write("    #back_to_top{\r\n");
      out.write("        display: block;\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 50%;\r\n");
      out.write("        right: 0;\r\n");
      out.write("        margin-top: -22px;\r\n");
      out.write("        background-position: -270px -123px;\r\n");
      out.write("        width: 44px;\r\n");
      out.write("        height: 44px;\r\n");
      out.write("        z-index: 1000;\r\n");
      out.write("        background: skyblue;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* inner 공간 분할 */\r\n");
      out.write("    #c_inner_top{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        background: white;\r\n");
      out.write("        border: 1px solid skyblue;\r\n");
      out.write("    }\r\n");
      out.write("    #c_inner_top .title1{\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        float: left;\r\n");
      out.write("        height: 100px;\r\n");
      out.write("        width: 166px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        background: skyblue;\r\n");
      out.write("    }\r\n");
      out.write("    #c_inner_top .title1 h2{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding-top: 30px;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    #c_inner_top .title2{\r\n");
      out.write("        width: 60px;\r\n");
      out.write("        float: left;\r\n");
      out.write("        height: 100px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #left_menu{\r\n");
      out.write("        width: 166px;\r\n");
      out.write("        float: left;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        display: block;\r\n");
      out.write("        border-bottom: 1px solid #dedede;\r\n");
      out.write("        border-top: 1px solid #dedede;\r\n");
      out.write("        border-left: 1px solid #dedede;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding-top: 20px;\r\n");
      out.write("        padding-left: 0;\r\n");
      out.write("        background: white;\r\n");
      out.write("    }\r\n");
      out.write("    #right_view{\r\n");
      out.write("        width: 822px;\r\n");
      out.write("        float: left;\r\n");
      out.write("        border: 1px solid #dedede;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        background: white;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* left_menu 관리 */\r\n");
      out.write("    #left_menu li{\r\n");
      out.write("        width: 132px;\r\n");
      out.write("        padding: 17px 0 15px 34px;\r\n");
      out.write("        border-bottom: 1px dashed #dedede;\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #left_menu .has_sub li{\r\n");
      out.write("        padding: 13px 0 0;\r\n");
      out.write("        height: 12px;\r\n");
      out.write("        border: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #left_menu .has_sub li a{\r\n");
      out.write("        color: darkgrey;\r\n");
      out.write("        font-size: 11px;\r\n");
      out.write("    }\r\n");
      out.write("    #left_menu .has_sub1 li{\r\n");
      out.write("        padding: 13px 0 0;\r\n");
      out.write("        height: 12px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        font-size: 13px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    #left_menu .has_sub1 a{\r\n");
      out.write("        color: lightskyblue;\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    #left_menu span{\r\n");
      out.write("        color: #444;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    /* right_view 내용 관리 */\r\n");
      out.write("    #right_view>.r_line{\r\n");
      out.write("        border-bottom: 2px solid gray;\r\n");
      out.write("        margin-bottom: 50px;\r\n");
      out.write("    }\r\n");
      out.write("    .r_table thead th{\r\n");
      out.write("        background: #f0f0f0;\r\n");
      out.write("        padding: 15px 0 15px;\r\n");
      out.write("        line-height: 11px;\r\n");
      out.write("        letter-spacing: -1px;\r\n");
      out.write("        color: grey;\r\n");
      out.write("    }\r\n");
      out.write("    .r_table table{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        border-spacing: 0;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .r_table td{\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        border-top: 1px solid #ececec;\r\n");
      out.write("        color: dimgray;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("    .cancelBtn{\r\n");
      out.write("        background-color: skyblue;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .paginate{\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding-top: 20px;\r\n");
      out.write("        border-top: 1px solid #c7c7c7;\r\n");
      out.write("    }\r\n");
      out.write("    .pagi_num{\r\n");
      out.write("        border: 1px solid skyblue;\r\n");
      out.write("        color: skyblue;\r\n");
      out.write("        padding: 5px 10px;\r\n");
      out.write("        margin: 2px;\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    /* 하단 회원 약관 */\r\n");
      out.write("    .note{\r\n");
      out.write("        background: #f4f4f4;\r\n");
      out.write("        padding: 26px 22px 20px;\r\n");
      out.write("        margin-top: 50px;\r\n");
      out.write("        line-height: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .note h6{\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("        color: #767676;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 6px;\r\n");
      out.write("    }\r\n");
      out.write("    .note ol{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .note ol li {\r\n");
      out.write("    padding-left: 6px;\r\n");
      out.write("    color: #999;\r\n");
      out.write("    font-size: 11px;\r\n");
      out.write("    letter-spacing: -1px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("    \r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("        $('.cancelBtn').click(function(){\r\n");
      out.write("            if(confirm(\"정말로 취소하시겠습니까?\")){\r\n");
      out.write("                alert(\"예매가 취소되었습니다.\");\r\n");
      out.write("            } else {\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("        <div id=\"h_inner\">\r\n");
      out.write("            <h1>TICKET SEA</h1>\r\n");
      out.write("        </div>        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("        <div id=\"c_inner\">\r\n");
      out.write("            <div id=\"c_inner_top\">\r\n");
      out.write("                <div class=\"title1\">\r\n");
      out.write("                    <h2>마이페이지</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"title2\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul id=\"left_menu\">\r\n");
      out.write("                <li class=\"has_sub1\">\r\n");
      out.write("                    <span>예매 관리</span>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"reserveList.jsp\">예매확인/취소</a>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"has_sub\">\r\n");
      out.write("                    <span>활동 관리</span>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"reviewMgr.jsp\">후기 관리</a></li>\r\n");
      out.write("                        <li><a href=\"faqMgr.jsp\">나의 문의 내역</a></li>\r\n");
      out.write("                        <li><a href=\"#\">소규모 공연 등록관리</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"has_sub\">\r\n");
      out.write("                    <span>회원정보관리</span>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"memberUpdate.jsp\">회원 정보 수정</a></li>\r\n");
      out.write("                        <li><a href=\"memberDelete.jsp\">회원 탈퇴</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>    \r\n");
      out.write("            <div id=\"right_view\">\r\n");
      out.write("                <div class=\"r_line\">\r\n");
      out.write("                    <h3>예매확인/취소</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"r_table\">\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>예매번호</th>\r\n");
      out.write("                                <th>티켓명</th>\r\n");
      out.write("                                <th>관람일시</th>\r\n");
      out.write("                                <th>매수</th>\r\n");
      out.write("                                <th>취소가능일</th>\r\n");
      out.write("                                <th>상태</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>1</td>\r\n");
      out.write("                                <td>라이온킹</td>\r\n");
      out.write("                                <td>18.10.11</td>\r\n");
      out.write("                                <td>2</td>\r\n");
      out.write("                                <td>18.10.01 까지</td>\r\n");
      out.write("                                <td>사용완료</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>2</td>\r\n");
      out.write("                                <td>라이온</td>\r\n");
      out.write("                                <td>18.11.20</td>\r\n");
      out.write("                                <td>3</td>\r\n");
      out.write("                                <td>18.11.10 까지</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <button class=\"cancelBtn\">취소</button>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <div class=\"paginate\">\r\n");
      out.write("                        \r\n");
      out.write("                        <a href=\"#\">처음</a>\r\n");
      out.write("                        \r\n");
      out.write("                        <a class=\"pagi_num\" href=\"#\">\r\n");
      out.write("                            <strong>1</strong>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        \r\n");
      out.write("                        <a class=\"pagi_num\" href=\"#\">\r\n");
      out.write("                            <strong>2</strong>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        \r\n");
      out.write("                        <a href=\"#\">끝</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"note\">\r\n");
      out.write("                    <h6>티켓취소 안내</h6>\r\n");
      out.write("                    <ol>\r\n");
      out.write("                            <li>예매한 티켓 전체 취소, 혹은 신용카드 결제 시 부분 취소가 가능합니다.<br>단, 일부 상품의 경우도 부분취소가 불가합니다.</li>\r\n");
      out.write("                            <li>티켓이 배송된 이후에는 인터넷이나 고객센터를 통한 취소가 불가하며, 받으신 티켓을 취소일 전까지 NHN티켓링크 본사로 반송을 해주셔야 취소 가능합니다. (등기우편을 이용해주세요!)</li>\r\n");
      out.write("                            <li>예매 당일 자정까지 취소하실 경우는 예매수수료도 환불되며, 취소수수료가 부과되지 않습니다. 그 이후에 취소하실 경우는 예매수수료가 환불되지 않으며, 취소수수료는 정책에 따라 부과됩니다.</li>\r\n");
      out.write("                            <li>일부 경기의 경우 상황에 따라 일괄 취소 건이 발생할 수있으며, 일괄 취소 시에는 취소 수수료가 부과되지 않습니다.</li>\r\n");
      out.write("                            <li>티켓의 날짜/시간/좌석 등급/좌석 위치 변경은 불가합니다. 자세한 안내가 필요할 경우 고객센터를 이용해주세요.</li>\r\n");
      out.write("                            <li>구단 홈페이지에서 예매한 내역은 구단 홈페이지에서만 확인이 가능합니다.</li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <a href=\"#\" id=\"back_to_top\">Top</a>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("        <div id=\"f_inner\">\r\n");
      out.write("            <strong class=\"footer_logo\">TICKET SEA</strong>\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"f_menu\">\r\n");
      out.write("                <a href=\"#\">사이트 소개</a><span>|</span>\r\n");
      out.write("                <a href=\"#\">개인정보 처리방침</a><span>|</span>\r\n");
      out.write("                <a href=\"#\">이용약관</a><span>|</span>\r\n");
      out.write("                <a href=\"#\">고객센터</a><span>|</span>\r\n");
      out.write("                <a href=\"#\">티켓판매안내</a><span>|</span>\r\n");
      out.write("                <a href=\"#\">광고안내</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("            <p class=\"copy\">Copyright © 옹가네 Corporation. All rights reserved.</p>\r\n");
      out.write("        </div>    \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
